import type { WordFormInput } from '@/lib/types';

/**
 * Twenty starter words, so a fresh install has something to study before you
 * have typed anything in. Loaded on demand from the empty word list, never
 * automatically - your own words should not arrive mixed in with these.
 *
 * Every example sentence here uses a form the matcher can find, so each word
 * gets all three question types.
 */
export const SEED_WORDS: WordFormInput[] = [
  {
    headword: 'ubiquitous',
    meaning_ko: '어디에나 있는, 편재하는',
    synonyms: ['omnipresent', 'pervasive', 'universal'],
    derived_words: [{ pos: 'n', word: 'ubiquity' }],
    examples: ['Smartphones have become ubiquitous in modern life.'],
    test_point: '"흔한(common)"보다 강한 뉘앙스로, 동시에 여러 곳에 존재한다는 의미',
  },
  {
    headword: 'mitigate',
    meaning_ko: '완화하다, 경감하다',
    synonyms: ['alleviate', 'lessen', 'ease'],
    derived_words: [{ pos: 'n', word: 'mitigation' }],
    examples: ['The new policy aims to mitigate the effects of air pollution.'],
    test_point: '나쁜 것의 정도를 줄일 때 사용. 문제 자체를 없애는 solve와 구분',
  },
  {
    headword: 'ambiguous',
    meaning_ko: '모호한, 두 가지 이상으로 해석되는',
    synonyms: ['vague', 'unclear', 'equivocal'],
    derived_words: [{ pos: 'n', word: 'ambiguity' }],
    examples: ['The instructions were so ambiguous that nobody knew what to do.'],
    test_point: '뜻이 여러 개라 헷갈리는 것. 단순히 정보가 부족한 obscure와 구분',
  },
  {
    headword: 'deteriorate',
    meaning_ko: '악화되다, 나빠지다',
    synonyms: ['worsen', 'decline', 'degenerate'],
    derived_words: [{ pos: 'n', word: 'deterioration' }],
    examples: ['Her health began to deteriorate after the surgery.'],
    test_point: '주로 자동사로 쓰여 상태가 스스로 나빠지는 것을 나타냄',
  },
  {
    headword: 'advocate',
    meaning_ko: '옹호하다, 지지하다 / 옹호자',
    synonyms: ['support', 'endorse', 'champion'],
    derived_words: [{ pos: 'n', word: 'advocacy' }],
    examples: ['Many scientists advocate stricter limits on carbon emissions.'],
    test_point: '동사와 명사 모두 가능. 명사일 때는 "지지자"',
  },
  {
    headword: 'plausible',
    meaning_ko: '그럴듯한, 타당해 보이는',
    synonyms: ['credible', 'believable', 'reasonable'],
    derived_words: [{ pos: 'n', word: 'plausibility' }],
    examples: ['He offered a plausible explanation for his absence.'],
    test_point: '실제로 사실인지와는 별개로 "말이 되어 보인다"는 뜻',
  },
  {
    headword: 'arbitrary',
    meaning_ko: '임의적인, 자의적인',
    synonyms: ['random', 'capricious', 'unreasoned'],
    derived_words: [{ pos: 'adv', word: 'arbitrarily' }],
    examples: ['The committee decision seemed completely arbitrary.'],
    test_point: '기준이나 근거 없이 정해졌다는 부정적 뉘앙스',
  },
  {
    headword: 'conspicuous',
    meaning_ko: '눈에 잘 띄는, 뚜렷한',
    synonyms: ['noticeable', 'prominent', 'striking'],
    derived_words: [{ pos: 'adv', word: 'conspicuously' }],
    examples: ['The red building was conspicuous among the gray offices.'],
    test_point: '반의어 inconspicuous(눈에 띄지 않는)와 함께 출제되는 경우가 많음',
  },
  {
    headword: 'diminish',
    meaning_ko: '줄어들다, 감소시키다',
    synonyms: ['decrease', 'reduce', 'dwindle'],
    derived_words: [{ pos: 'n', word: 'diminution' }],
    examples: ['Interest in the project diminished over time.'],
    test_point: '자동사와 타동사 모두 가능',
  },
  {
    headword: 'coherent',
    meaning_ko: '일관성 있는, 논리 정연한',
    synonyms: ['logical', 'consistent', 'unified'],
    derived_words: [{ pos: 'n', word: 'coherence' }],
    examples: ['She presented a coherent argument for the reform.'],
    test_point: '부분들이 논리적으로 맞물려 있다는 의미',
  },
  {
    headword: 'exacerbate',
    meaning_ko: '악화시키다, 더 심하게 만들다',
    synonyms: ['aggravate', 'intensify', 'worsen'],
    derived_words: [{ pos: 'n', word: 'exacerbation' }],
    examples: ['Cutting the budget would only exacerbate the problem.'],
    test_point: '타동사. 스스로 나빠지는 deteriorate와 방향이 반대',
  },
  {
    headword: 'prevalent',
    meaning_ko: '널리 퍼진, 만연한',
    synonyms: ['widespread', 'common', 'rife'],
    derived_words: [{ pos: 'n', word: 'prevalence' }],
    examples: ['This species is prevalent along the eastern coast.'],
    test_point: '특정 지역이나 집단에서 흔하다는 뜻',
  },
  {
    headword: 'scrutinize',
    meaning_ko: '면밀히 조사하다, 자세히 살피다',
    synonyms: ['examine', 'inspect', 'analyze'],
    derived_words: [{ pos: 'n', word: 'scrutiny' }],
    examples: ['Auditors scrutinize every transaction in the report.'],
    test_point: '그냥 보는 것이 아니라 아주 꼼꼼히 본다는 강조',
  },
  {
    headword: 'tentative',
    meaning_ko: '잠정적인, 확정되지 않은',
    synonyms: ['provisional', 'preliminary', 'unconfirmed'],
    derived_words: [{ pos: 'adv', word: 'tentatively' }],
    examples: ['They reached a tentative agreement on the schedule.'],
    test_point: '"임시" 의미와 "머뭇거리는" 의미 두 가지로 모두 출제됨',
  },
  {
    headword: 'viable',
    meaning_ko: '실행 가능한, 생존 가능한',
    synonyms: ['feasible', 'workable', 'practicable'],
    derived_words: [{ pos: 'n', word: 'viability' }],
    examples: ['Solar power is now a viable alternative to coal.'],
    test_point: '생물학 지문에서는 "생존 가능한"으로 해석',
  },
  {
    headword: 'resilient',
    meaning_ko: '회복력 있는, 탄력 있는',
    synonyms: ['tough', 'adaptable', 'hardy'],
    derived_words: [{ pos: 'n', word: 'resilience' }],
    examples: ['Coral reefs are less resilient than they once were.'],
    test_point: '충격을 받은 뒤 원래 상태로 돌아오는 능력',
  },
  {
    headword: 'abundant',
    meaning_ko: '풍부한, 많은',
    synonyms: ['plentiful', 'ample', 'copious'],
    derived_words: [{ pos: 'n', word: 'abundance' }],
    examples: ['Fossils are abundant in this region.'],
    test_point: '반의어 scarce(부족한)와 짝으로 자주 출제',
  },
  {
    headword: 'deliberate',
    meaning_ko: '의도적인 / 숙고하다',
    synonyms: ['intentional', 'calculated', 'premeditated'],
    derived_words: [{ pos: 'adv', word: 'deliberately' }],
    examples: ['The omission was deliberate, not an oversight.'],
    test_point: '형용사(의도적인)와 동사(숙고하다)의 발음과 뜻이 모두 다름',
  },
  {
    headword: 'intricate',
    meaning_ko: '복잡한, 정교한',
    synonyms: ['complex', 'elaborate', 'convoluted'],
    derived_words: [{ pos: 'n', word: 'intricacy' }],
    examples: ['The clock contains an intricate system of gears.'],
    test_point: '부정적인 "복잡함"보다 정교하다는 뉘앙스가 강함',
  },
  {
    headword: 'obsolete',
    meaning_ko: '구식의, 더 이상 쓰이지 않는',
    synonyms: ['outdated', 'antiquated', 'outmoded'],
    derived_words: [{ pos: 'n', word: 'obsolescence' }],
    examples: ['Typewriters became obsolete once computers arrived.'],
    test_point: '기술·제도가 새것에 밀려 쓸모없어진 상태',
  },
];
